sql:
  host: "localhost"
  port: 3306
  user: "root"
  password: ""
  database: "test"

redis:
  host: "127.0.0.1"
  port: "6379"

black-market-chance: 10

webhook:
  url: "https://discord.com/api/webhooks/1274624946949197906/63UlmNH6KLKD7lxEz0gQlT8d_CGbNXJ3M6tG__FJT5pZOizKt0mZnhD0WtKcts3xRfCD"
  message: "{player} bought {item} x{amount} from {market} for the price of: {price}$!"

confirm-gui:
  accept:
    name: "<green>Accept"
    material: "GREEN_STAINED_GLASS_PANE"
    lore:
      - ' '
  reject:
    name: "<red>Reject"
    material: "RED_STAINED_GLASS_PANE"
    lore:
      - ' '